### ISSUE TITLE
how to decide a sql string is standard or extended

### ISSUE THREAD

**Issue by weiguoz** [wangkuiyi/sqlflowserver#6]
```language=go
if (strings.Contains(slct, "TRAIN") || strings.Contains(slct, "PREDICT") {
    return "extended"
}
```
的方式可能会误判，比如`select * from TRAIN_XX` 这里TRAIN_XX是表名。
没有想好怎么解决，先抛出来讨论一下，或许在语法解析时才能准确判断。

**Comment by wangkuiyi** [comment]
Good catch! 貌似应该用 https://golang.org/pkg/strings/#HasPrefix

**Comment by wangkuiyi** [comment]
精确的判断可以通过先parse，然后检查 parser 生成的以下 struct 里

https://github.com/wangkuiyi/sqlflow/blob/602a227c7ec685600a636c24ff6c8ce41b9aa9f3/sql/sql.y#L60-L62

`extended` 是否为 true 来决定。

**Comment by tonyyang-svail** [comment]
> 精确的判断可以通过先parse，然后检查 parser 生成的以下 struct 里
> 
> https://github.com/wangkuiyi/sqlflow/blob/602a227c7ec685600a636c24ff6c8ce41b9aa9f3/sql/sql.y#L60-L62
> 
> `extended` 是否为 true 来决定。

如果用户写的standardSQL不能被`sql.y` parse怎么办呢？

**Comment by ktong** [comment]
sql不能解析还能干啥：）报错呀：）
