### ISSUE TITLE
Add a python rpc client which connects to the minimum server

### ISSUE THREAD

**Issue by weiguoz** [wangkuiyi/sqlflowserver#8]

**Comment by wangkuiyi** [comment]
I am not sure if we need to do this in this repo. I think @ktong might do this in https://github.com/ktong/pysqlflow/

**Comment by weiguoz** [comment]
> I am not sure if we need to do this in this repo. I think @ktong might do this in https://github.com/ktong/pysqlflow/

我原想尝试magic command和sqlflowserver的连接做试验。如果pysqlflow近期做的话，我close掉这个issue

**Comment by wangkuiyi** [comment]
我们都也可以向 https://github.com/ktong/pysqlflow/ 贡献代码的。

从 .proto 生成 Python 的 client 代码我理解运行一行命令即可（https://grpc.io/docs/tutorials/basic/python.html）：

```bash
python -m grpc_tools.protoc -I../../protos --python_out=. --grpc_python_out=. ../../protos/route_guide.proto
```

所以自己做个试验应该也挺方便的。
